### ISSUE TITLE
Unable to run the web app in Ubuntu VM

### ISSUE THREAD

**Issue by monitoringhsd** [PMA-2020/ppp-web#50]
## Steps to Reproduce

Followed instructions for ppp-web in Ubuntu VM on Azure.

## Desired/expected behavior 

Should be able to launch the app.

## Actual behavior 

From Terminal:

> (.venv) root@ppp-web:/opt/ppp-web/ppp_web# gunicorn -b 0.0.0.0:8080 run:app_instance &
> [1] 11527
> (.venv) root@ppp-web:/opt/ppp-web/ppp_web# [2023-01-20 12:03:16 +0000] [11527] [INFO] Starting gunicorn 20.1.0
> [2023-01-20 12:03:16 +0000] [11527] [INFO] Listening at: http://0.0.0.0:8080 (11527)
> [2023-01-20 12:03:16 +0000] [11527] [INFO] Using worker: sync
> [2023-01-20 12:03:16 +0000] [11529] [INFO] Booting worker with pid: 11529
> [2023-01-20 12:03:16 +0000] [11529] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
>     worker.init_process()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
>     self.load_wsgi()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
>     return self.load_wsgiapp()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
>     mod = importlib.import_module(module)
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'run'
> [2023-01-20 12:03:16 +0000] [11529] [INFO] Worker exiting (pid: 11529)
> [2023-01-20 12:03:16 +0000] [11527] [INFO] Shutting down: Master
> [2023-01-20 12:03:16 +0000] [11527] [INFO] Reason: Worker failed to boot.

Any advice would be appreciated. Thanks!

**Comment by jkpr** [comment]
maybe?

```
gunicorn -b 0.0.0.0:8080 ppp_web:run &
```

**Comment by monitoringhsd** [comment]
Many thanks for your reply, but it did not help, unfortunately.

I have tried it again on a freshly rebooted VM and got the following:

> root@ppp-web:~# cd /opt/ppp-web
> root@ppp-web:/opt/ppp-web# source .venv/bin/activate
> (.venv) root@ppp-web:/opt/ppp-web# cd /opt/ppp-web/ppp_web
> (.venv) root@ppp-web:/opt/ppp-web/ppp_web# gunicorn -b 0.0.0.0:8080 ppp_web:run &
> [1] 1099
> (.venv) root@ppp-web:/opt/ppp-web/ppp_web# [2023-01-20 18:56:37 +0000] [1099] [INFO] Starting gunicorn 20.1.0
> [2023-01-20 18:56:37 +0000] [1099] [INFO] Listening at: http://0.0.0.0:8080 (1099)
> [2023-01-20 18:56:37 +0000] [1099] [INFO] Using worker: sync
> [2023-01-20 18:56:37 +0000] [1101] [INFO] Booting worker with pid: 1101
> [2023-01-20 18:56:37 +0000] [1101] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/opt/ppp-web/ppp_web/ppp_web.py", line 23, in add_views
>     from ppp_web.views import IndexView
> ModuleNotFoundError: No module named 'ppp_web.views'; 'ppp_web' is not a package
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
>     worker.init_process()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
>     self.load_wsgi()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
>     return self.load_wsgiapp()
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
>     return util.import_app(self.app_uri)
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
>     mod = importlib.import_module(module)
>   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/opt/ppp-web/ppp_web/ppp_web.py", line 45, in <module>
>     app = create_app()
>   File "/opt/ppp-web/ppp_web/ppp_web.py", line 41, in create_app
>     add_views(new_app)
>   File "/opt/ppp-web/ppp_web/ppp_web.py", line 25, in add_views
>     from views import IndexView
>   File "/opt/ppp-web/ppp_web/views.py", line 17, in <module>
>     from ppp import run, OdkException
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/ppp/__init__.py", line 31, in <module>
>     from ppp.odkform import OdkForm, set_template_env
>   File "/opt/ppp-web/.venv/lib/python3.8/site-packages/ppp/odkform.py", line 18, in <module>
>     from pmix import Xlsform
> ImportError: cannot import name 'Xlsform' from 'pmix' (/opt/ppp-web/.venv/lib/python3.8/site-packages/pmix/__init__.py)
> [2023-01-20 18:56:37 +0000] [1101] [INFO] Worker exiting (pid: 1101)
> [2023-01-20 18:56:37 +0000] [1099] [INFO] Shutting down: Master
> [2023-01-20 18:56:37 +0000] [1099] [INFO] Reason: Worker failed to boot.
> (.venv) root@ppp-web:/opt/ppp-web/ppp_web#

**Comment by monitoringhsd** [comment]
Then, I have installed the app without a virtual environment, since this VM has been created specifically to test the ppp-web app and got an "Internal server error" in the browser.

Here is the output:

> root@ppp-web:~# cd ppp-web
> root@ppp-web:~/ppp-web# cd ppp_web
> root@ppp-web:~/ppp-web/ppp_web# gunicorn -b 0.0.0.0:8080 ppp_web:run &
> [1] 1124
> root@ppp-web:~/ppp-web/ppp_web# [2023-01-20 19:02:19 +0000] [1124] [INFO] Starting gunicorn 19.9.0
> [2023-01-20 19:02:19 +0000] [1124] [INFO] Listening at: http://0.0.0.0:8080 (1124)
> [2023-01-20 19:02:19 +0000] [1124] [INFO] Using worker: sync
> /usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
>   return io.open(fd, *args, **kwargs)
> [2023-01-20 19:02:19 +0000] [1126] [INFO] Booting worker with pid: 1126
> [2023-01-20 19:02:55 +0000] [1126] [ERROR] Error handling request /
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 135, in handle
>     self.handle_request(listener, req, client, addr)
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
> TypeError: run() takes 0 positional arguments but 2 were given
> [2023-01-20 19:02:56 +0000] [1126] [ERROR] Error handling request /favicon.ico
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 135, in handle
>     self.handle_request(listener, req, client, addr)
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
> TypeError: run() takes 0 positional arguments but 2 were given

**Comment by jkpr** [comment]
Sorry it isn't working. This is an unmaintained project. Pmix is a dependency of ppp. So you would have to install that first. It is on pypi: https://pypi.org/project/pmix/

**Comment by monitoringhsd** [comment]
Thanks for letting me know that is unmaintained. 
Regarding pmix, I have it installed too. 

> (.venv) root@ppp-web:/opt/ppp-web# pip install pmix
> Requirement already satisfied: pmix in ./.venv/lib/python3.8/site-packages (0.4.0)
> Requirement already satisfied: XlsxWriter>=1.1.0 in ./.venv/lib/python3.8/site-packages (from pmix) (1.1.0)
> Requirement already satisfied: xlrd>=1.1.0 in ./.venv/lib/python3.8/site-packages (from pmix) (1.1.0)

Well, looks like I will have to use a command line tool instead of the web app.

**Comment by joeflack4** [comment]
I was going to respond to this but somehow it fell off my radar, sorry.

I'm not sure I'll be much help either ;(. Strapped for time; sorry about this project not being maintained.

As far as what I can tell so far...
```py
from ppp_web.views import IndexView
ModuleNotFoundError: No module named 'ppp_web.views'; 'ppp_web' is not a package
```

It looks like we don't have robustness here to handle the users present working directory. You're running the `gunicorn` command from within the `ppp_web` directory, which is not bad in theory, but the way we have our imports set up, it looks like it probably needs you to be in the root directory; the directory w/ the `.gitignore`, `README.md`, etc.

I'm not sure if it's a `pmix` dependency issue that is the problem. It looks like you have it installed.

I looked at the documentation as well as `ppp_web/ppp_web.py`. There's a chance 
I think maybe you should give this a shot, but I don't know if it'll work:

**Try this:**
From the root directory of the repository, run:
`gunicorn -b 0.0.0.0:8080 ppp_web.ppp_web:app &`

The reason I think this is because, from [gunicorn docs](https://docs.gunicorn.org/en/stable/run.html#commands):
> Where WSGI_APP is of the pattern `$(MODULE_NAME):$(VARIABLE_NAME)`. The module name can be a full dotted path. The variable name refers to a WSGI callable that should be found in the specified module.

In the `gunicorn` command above, `$(MODULE_NAME)` would be `ppp_web.ppp_web`, and `$(VARIABLE_NAME)` would be `app`.

I think if you run that command above, it will also address this issue: `TypeError: run() takes 0 positional arguments but 2 were given`

**Comment by monitoringhsd** [comment]
Many thanks for your kind suggestion, @joeflack4. It has worked. I was able to launch the app and access it in a browser. 

`(.venv) root@ppp-web:/opt/ppp-web# gunicorn -b 0.0.0.0:8080 ppp_web.ppp_web:app &
[1] 22543`
`(.venv) root@ppp-web:/opt/ppp-web# [2023-02-08 16:17:29 +0000] [22543] [INFO] Starting gunicorn 19.9.0`
`[2023-02-08 16:17:29 +0000] [22543] [INFO] Listening at: http://0.0.0.0:8080 (22543)`
`[2023-02-08 16:17:29 +0000] [22543] [INFO] Using worker: sync`
`[2023-02-08 16:17:29 +0000] [22546] [INFO] Booting worker with pid: 22546`

However, when I try to convert an XLS file the webpage crashes, showing "This page isn’t working right now" and "didn’t send any data". Do you have any idea why it might happen? 
The port 8080 is opened for the VM in outbound and inbound rules. 

Also, just to let you know, the following example line from the instructions does not work:
`pip install https://github.com/joeflack4/pmix/archive/ppp.zip`
So, I assumed that the first one was enough:
`pip install https://github.com/jkpr/pmix/archive/develop.zip`

**Comment by joeflack4** [comment]
Oh man I'm glad that worked and go the app up and running!

**XLS conversion errors**
As for why this new issue is happening, I'm not sure... One would have to debug it or check the logs. Can you check the logs? It looks like they should be at:
`logs/error-logfile.log`

**pmix**
As for the `pip install ... *.zip`, it's been forever and I don't remember why these different distributions of `pmix`. I'm glad you got one of them installed, though. I think the one you installed should be sufficient. Also it looks like `pmix` version `0.7.0` is available on PyPi via `pip install pmix`. But I'm not sure if it is as up-to-date as `pip install https://github.com/jkpr/pmix/archive/develop.zip`.

**Comment by monitoringhsd** [comment]
Unfortunately, the log files are empty. Perhaps the directory isn't in the right place...
Could you please let me know where exactly should the logs directory be located?
It is not really clear to me from the tutorial. It is currently here (inside the virtual environment):
`(.venv) root@ppp-web:~/logs#`

But when in Terminal, I get the following when the app is running and I try to convert the file:

`[2023-02-09 08:37:00 +0000] [11538] [INFO] Listening at: http://0.0.0.0:8080 (11538)`
`[2023-02-09 08:37:00 +0000] [11538] [INFO] Using worker: sync`
`[2023-02-09 08:37:00 +0000] [11541] [INFO] Booting worker with pid: 11541`
`Creating files.`
`--Return--`
`> /opt/ppp-web/ppp_web/views.py(199)_run_ppp_api()->None`
`-> from pdb import set_trace; set_trace()`
`[2023-02-09 08:37:22 +0000] [11538] [INFO] Handling signal: ttou`
`[2023-02-09 08:37:22 +0000] [11538] [INFO] Handling signal: ttou`
`[2023-02-09 08:37:22 +0000] [11538] [INFO] Handling signal: ttou`
...
`[2023-02-09 08:37:51 +0000] [11538] [CRITICAL] WORKER TIMEOUT (pid:11541)`
`[2023-02-09 08:37:51 +0000] [11538] [INFO] Handling signal: ttou`
`[2023-02-09 08:37:51 +0000] [11544] [INFO] Booting worker with pid: 11544`

**Comment by joeflack4** [comment]
Ahh, interesting.

**`from pdb import set_trace; set_trace()`**
If this is in the release version of the code, I'm surprised. This should only be there in development. `set_trace()` is a breakpoint (`pdb` stands for python debugger). You'll need to remove that line (`ppp_web/views.py(199)`).

**Logs**
I think the reason the logs are not there, probably, is because the `gunicorn` command being used to run the server doesn't have any of the logs flags. At the minimum, you'll want to use `--error-logfile path/to/whereYouWantLogfile`. See: https://docs.gunicorn.org/en/stable/settings.html#errorlog

The `README.md` should include this as part of `gunicorn` command for the deployment.

**Comment by monitoringhsd** [comment]
Well, I have searched through views.py and I am a bit confused since there is no line `_run_ppp_api()->None`

There is this part of code that has `set_trace()` at the end:

```
   @staticmethod
    def _run_ppp_api(in_file_path, out_format, out_file_path):
        language = request.form.get('language')
        lang_option = language if language and language != 'none' else ''
        preset = request.form.get('preset', 'standard')
        try:
            run(files=[in_file_path],
                languages=[lang_option],
                format=out_format,
                preset=preset,
                template='old',
                outpath=out_file_path)
            return True  # ?
            # some logic
        except OdkException as err:
            return err
        except Exception as err:
            from pdb import set_trace; set_trace()
```

**Comment by monitoringhsd** [comment]
I have tested by removing the following 

```
except Exception as err:
            from pdb import set_trace; set_trace()
```
Then, restarted the app and tried to convert demo.xlsx again, and got the following in the Terminal:

```
Creating files.
[2023-02-09 20:51:58 +0000] [3509] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/ppp-web/ppp_web/views.py", line 80, in post
    out_file_path=html_file_path)
  File "/opt/ppp-web/ppp_web/views.py", line 193, in _run_ppp_api
    outpath=out_file_path)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/__init__.py", line 158, in run
    convert_file(file, language, outpath=_outpath, **combo)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/__init__.py", line 52, in convert_file
    form = OdkForm.from_file(in_file)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkform.py", line 111, in from_file
    if xlsform.warnings:
AttributeError: 'Xlsform' object has no attribute 'warnings'
```

In the browser: **Internal Server Error**

**Comment by joeflack4** [comment]
**edit**: I just saw you already tried out one of the recommendations below. Take a look at my [next comment](https://github.com/pmaengineering/ppp-web/issues/50#issuecomment-1424845169) which has a solution to your current problem.

---

Yep, that's it!

So what we're looking at is a function/method `_run_ppp_api()` that doesn't return anything; hence why the stacktrace added a `->None` to the end, it looks like.

It tries to do the conversion, and if it gets an expected error (`OdkException`), it returns that error. But if it gets an unanticipated exception, it enters the debugger (`from pdb import set_trace; set_trace()`; the final line of that function).

This makes sense for development, but for the `main` branch / production code that is actually supposed to run on the server, that shouldn't be there. There are a variety of things that you could do, but I think you should try 1 or more of the following and see what works out best: 

Change this
```py
        except Exception as err:
            from pdb import set_trace; set_trace()
```

a. Simply delete these two lines. If it gets an unanticipated exception, it'll raise the error, and that should show up in the logs.

b. Replace it with:
At top of the file, add this if it's not there already: `import sys`
```py
        except Exception as err:
            print(err, file=sys.stderr)
            raise err
```


c. You could try the same thing as (b) but do `return err` instead of `raise err`

d. You could try the same thing as (b) but do `return err`, do nothing after the `print()`.

e. I am thinking that these `raise` and `print` statements should show up in the log (once you update how `gunicorn` is being run as I was [mentioning earlier](https://github.com/pmaengineering/ppp-web/issues/50#issuecomment-1424739136)), but if they don't show up in the logs, perhaps there's something you should use instead of `print()` in order to get the error to show up in the logs.

**Comment by joeflack4** [comment]
Alright, I looked at your updated response, and here's what I found.

This is a problem not in `ppp-web`, but in the `ppp` repo (same thing as `odk-ppp` on pip / PyPi).

The `develop` branch has this line which is causing the error:
https://github.com/pmaengineering/ppp/blob/develop/ppp/odkform.py#L114
https://github.com/pmaengineering/ppp/blob/develop/ppp/odkform.py#L102-L123

The `master` branch is newer, and doesn't have that error
https://github.com/pmaengineering/ppp/blob/master/ppp/odkform.py#L111-L113

It looks like the `requirements.txt` for `ppp-web` did not get updated when the newer release of `odk-ppp` came out. I think what you should do is edit `requirements.txt` so that it is installing the latest version of `odk-ppp` Right now it says `odk-ppp==1.2.8`. Change it to say `odk-ppp==`1.4.0`.

You can then install it; you don't have to run `pip install -r requirements.txt` again; you can just do `pip install --upgrade odk-ppp`.

Then try things again and let us know!

**Comment by monitoringhsd** [comment]
Thanks a lot for your time and kind suggestions. I have tried to follow and started from scratch. 
1. Stopped the app and removed web-ppp directory. 
2. wget ppp-web.git
3. in requirements.txt, changed to odk-ppp==1.4.0
3.1 also needed to change to pmix==0.7.0, because running the following `pip3 install -r requirements.txt` gave an error that pmix should be 0.7.0 or above.
4. created `app_instance/config.py` and added `PYTHON_PATH`, although I am not sure it is needed since `app_instance` is not being run (but let me know what you think)
5. `chmod +x bin/wkhtmltopdf` per instructions
6. `mkdir logs/` in `/opt/ppp-web/ppp_web` with log files (will look into `gunicorn` later)
7. finally: `/opt/ppp-web/ $ gunicorn -b 0.0.0.0:8080 ppp_web.ppp_web:app &`
8. but got a new error in Terminal when trying to convert demo.xlsx:
9. **edit:** forgot to add that I also needed to remove (as discussed above) the following from views.py:
```
except Exception as err:
            from pdb import set_trace; set_trace()
```

```
Creating files.
[2023-02-09 21:26:41 +0000] [3807] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/ppp-web/ppp_web/views.py", line 80, in post
    out_file_path=html_file_path)
  File "/opt/ppp-web/ppp_web/views.py", line 193, in _run_ppp_api
    outpath=out_file_path)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/__init__.py", line 165, in run
    convert_file(file, language, outpath=_outpath, **combo)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/__init__.py", line 62, in convert_file
    output = form.to_html(lang=language, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkform.py", line 445, in to_html
    html = item.to_html(lang=language, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkprompt.py", line 637, in to_html
    settings = self.html_options(lang=lang, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkprompt.py", line 619, in html_options
    for k, v in TEMPLATES[kwargs["template"]]["render_settings"]["html"].items():
KeyError: 'old'
```

**Comment by monitoringhsd** [comment]
Just wanted to comment regarding logs with `gunicorn`, as I have probably figured it out. Thanks for the link to the settings.
Here is what I did:
1. stopped the process by finding it (`ps -e | grep gunicorn`) and killing it (`kill -9 <ID>`)
2. created a new file in logs directory (`cd /opt/ppp-web/ppp_web/logs`), called `gunicornlog.log`
3. when running the app again from `/opt/ppp-web/`, added settings to `gunicorn`: 
`GUNICORN_CMD_ARGS="--error-logfile /opt/ppp-web/ppp_web/logs/gunicornlog.log" gunicorn -b 0.0.0.0:8080 ppp_web.ppp_web:app &`
4. tried to convert demo.xlsx and checked what was inside `gunicornlog.log`:

```
[2023-02-10 08:23:55 +0000] [7121] [INFO] Starting gunicorn 19.9.0
[2023-02-10 08:23:55 +0000] [7121] [INFO] Listening at: http://0.0.0.0:8080 (7121)
[2023-02-10 08:23:55 +0000] [7121] [INFO] Using worker: sync
[2023-02-10 08:23:55 +0000] [7124] [INFO] Booting worker with pid: 7124
[2023-02-10 08:24:27 +0000] [7124] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/ppp-web/ppp_web/views.py", line 80, in post
    out_file_path=html_file_path)
  File "/opt/ppp-web/ppp_web/views.py", line 193, in _run_ppp_api
    outpath=out_file_path)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/__init__.py", line 165, in run
    convert_file(file, language, outpath=_outpath, **combo)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/__init__.py", line 62, in convert_file
    output = form.to_html(lang=language, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkform.py", line 445, in to_html
    html = item.to_html(lang=language, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkprompt.py", line 637, in to_html
    settings = self.html_options(lang=lang, **kwargs)
  File "/opt/ppp-web/.venv/lib/python3.6/site-packages/ppp/odkprompt.py", line 619, in html_options
    for k, v in TEMPLATES[kwargs["template"]]["render_settings"]["html"].items():
KeyError: 'old'
```
So, the error is the same as in the previous message.

**Comment by joeflack4** [comment]
That's great that the logs are figured out.

As for this error, I have a suspicion that there is some template called 'old' which was removed and is causing this. I'm short on time though and I'll see if I can look at this again on Sunday.

**Comment by monitoringhsd** [comment]
Okay, no problem. Any help in fixing it at some point would be very much appreciated. This tool is the best that I could find when it comes to converting XLS Forms to nicely formatted Word documents. We do a lot of data collection with ODK at WHO, and this tool is invaluable. 
I just can't understand why the original website on heroku worked fine if it was based on the same repository and stuff...

**Comment by joeflack4** [comment]
Hey @monitoringhsd , sorry for the delay. I just took a look, and I encountered my own error (different than what you encountered). What were the options that you had selected when you uploaded and got the error?

For me, I just had:
- file: demo.xlsx
- Format: doc
- Language: English
- Preset: Standard

Also, I'm sorry to say, but James and I don't reliably have available time to offer support. I would consider offering you guys a kind of support plan (even if it's just fixing a few bugs and that's it) if this is something you / your team would like. My email is joeflack4@gmail.com if that is something you'd like.

**Comment by monitoringhsd** [comment]
Thanks for getting back on this. I simply uploaded the demo file with the same options: doc, English, standard. 
If you encountered an error, are you not supposed to correct it and push to the github so that the project is not broken? Otherwise, it is not going to be used by anyone. But it is up to you of course.
So far, I have been using the command line tool, which works fine. The web app just provided a cleaner output for some reason. That is one of the main reasons, I wanted to test it. We shall see how it goes later on. Thanks for the offer though.

**Comment by joeflack4** [comment]
Hey @monitoringhsd . Ah OK, so same options as me. I think I got a different error than you because of a Mac-specific issue.

I agree w/ you, and I love this tool. But I haven't worked for PMA in 3 years and it doesn't look like they are maintaining it. I'm not sure if anyone other than James and I have really worked on it, and it seems like both of us are very limited in our free time to help maintain our past projects.

**Comment by monitoringhsd** [comment]
The website is back online - http://ppp.pma2020.org/. I guess someone of you guys moved it to another hosting server. 
I have noticed however that that it is "PPP-Web Version: 1.3.1", which is not available on GitHub. I wonder if it can be accessed somewhere for testing or it is not for public use?

**Comment by joeflack4** [comment]
Wow, well that's convenient. It wasn't me. Not sure if James (jkpr@) did it. I'm not even sure who within PMA to contact now about this kinda stuff, though I could probably find out.
